services:
  postgres:
    container_name: 'BankingDatabase'
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=banking_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=user'
    ports:
      - '5442:5432'
