spring:
  flyway:
    user: user
    password: secret
    url: jdbc:postgresql://localhost5442/banking_db
    schemas: domain, public
    enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
           time_zone: 'UTC'
        check_nullability: true
        hikari:
          jdbcUrl: jdbc:postgresql://localhost5442/banking_db
          username: user
          password: secret
          autocommit: false
        default_schema: domain
        preferred_uuid_jdbc_type: 3000
        show_sql: true
        format_sql: true
        highlight_sql: true